@startuml "Phrase"

abstract class Instruction

class InstructionDQL {
    +CommandeDQL
    +Body
}
class InstructionDML {
    +CommandeDML
    +Body
}

abstract class Commande

class CommandeDQL
class CommandeDML


'Héritage

Instruction <|-- InstructionDQL
Instruction <|-- InstructionDML

Commande <|-- CommandeDQL
Commande <|-- CommandeDML

InstructionDQL o-- CommandeDQL
InstructionDML o-- CommandeDML

@enduml