CREATE (Alice);

CREATE (Bob:PERSONNE:GEEK);

CREATE (Charlie {nom:"Charlie", annee_naissance:2000});

CREATE ({name:"Danny", annee_naissance:1990});


CREATE (Alice)-[:FRIEND]->(Bob);

CREATE (Alice)-[:EMPLOYED_BY {company:"NVIDIA", since: 2020}]->(Charlie)


DUMP;